# Example ESPHome configuration for Kocom RS485 wallpad integration
# Adjust pins, room indices, and device counts to match your apartment.

esphome:
  name: kocom-wallpad
  friendly_name: Kocom Wallpad

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

# --- External component ---

external_components:
  - source:
      type: git
      url: https://github.com/import-shiburin/esphome-kocom-rs485
    components: [kocom_rs485]

# --- UART for RS485 transceiver ---

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# --- Kocom RS485 main component ---

kocom_rs485:
  id: kocom
  uart_id: uart_bus
  rooms:
    # Living room: 3 lights, 2 plugs
    - index: 0
      light_count: 3
      light_ids:
        - living_light_1
        - living_light_2
        - living_light_3
      plug_count: 2

    # Bedroom: 2 lights, 1 plug
    - index: 1
      light_count: 2
      light_ids:
        - bedroom_light_1
        - bedroom_light_2
      plug_count: 1

    # Room 2: 1 light
    - index: 2
      light_count: 1
      light_ids:
        - room2_light_1

  # Elevator arrival binary sensor
  elevator_arrived:
    name: "Elevator Arrived"

# ============================================================
#  Lights
#  Each light needs a template output that calls set_light().
# ============================================================

output:
  # --- Living room outputs ---
  - platform: template
    id: living_light_1_out
    type: binary
    write_action:
      - lambda: id(kocom).set_light(0, 0, state);
  - platform: template
    id: living_light_2_out
    type: binary
    write_action:
      - lambda: id(kocom).set_light(0, 1, state);
  - platform: template
    id: living_light_3_out
    type: binary
    write_action:
      - lambda: id(kocom).set_light(0, 2, state);

  # --- Bedroom outputs ---
  - platform: template
    id: bedroom_light_1_out
    type: binary
    write_action:
      - lambda: id(kocom).set_light(1, 0, state);
  - platform: template
    id: bedroom_light_2_out
    type: binary
    write_action:
      - lambda: id(kocom).set_light(1, 1, state);

  # --- Room 2 output ---
  - platform: template
    id: room2_light_1_out
    type: binary
    write_action:
      - lambda: id(kocom).set_light(2, 0, state);

light:
  # --- Living room lights ---
  - platform: binary
    id: living_light_1
    name: "Living Room Light 1"
    output: living_light_1_out
  - platform: binary
    id: living_light_2
    name: "Living Room Light 2"
    output: living_light_2_out
  - platform: binary
    id: living_light_3
    name: "Living Room Light 3"
    output: living_light_3_out

  # --- Bedroom lights ---
  - platform: binary
    id: bedroom_light_1
    name: "Bedroom Light 1"
    output: bedroom_light_1_out
  - platform: binary
    id: bedroom_light_2
    name: "Bedroom Light 2"
    output: bedroom_light_2_out

  # --- Room 2 light ---
  - platform: binary
    id: room2_light_1
    name: "Room 2 Light"
    output: room2_light_1_out

# ============================================================
#  Thermostats (climate)
# ============================================================

climate:
  - platform: kocom_rs485
    kocom_rs485_id: kocom
    room: 0
    name: "Living Room Thermostat"

  - platform: kocom_rs485
    kocom_rs485_id: kocom
    room: 1
    name: "Bedroom Thermostat"

  - platform: kocom_rs485
    kocom_rs485_id: kocom
    room: 2
    name: "Room 2 Thermostat"

  - platform: kocom_rs485
    kocom_rs485_id: kocom
    room: 3
    name: "Room 3 Thermostat"

# ============================================================
#  Ventilation fan
# ============================================================

fan:
  - platform: kocom_rs485
    kocom_rs485_id: kocom
    name: "Ventilation Fan"
    speed_count: 3

# ============================================================
#  Plugs (template switches)
# ============================================================

switch:
  # --- Living room plugs ---
  - platform: template
    name: "Living Room Plug 1"
    lambda: return id(kocom).get_plug(0, 0);
    turn_on_action:
      - lambda: id(kocom).set_plug(0, 0, true);
    turn_off_action:
      - lambda: id(kocom).set_plug(0, 0, false);

  - platform: template
    name: "Living Room Plug 2"
    lambda: return id(kocom).get_plug(0, 1);
    turn_on_action:
      - lambda: id(kocom).set_plug(0, 1, true);
    turn_off_action:
      - lambda: id(kocom).set_plug(0, 1, false);

  # --- Bedroom plug ---
  - platform: template
    name: "Bedroom Plug 1"
    lambda: return id(kocom).get_plug(1, 0);
    turn_on_action:
      - lambda: id(kocom).set_plug(1, 0, true);
    turn_off_action:
      - lambda: id(kocom).set_plug(1, 0, false);

# ============================================================
#  Elevator
# ============================================================

button:
  - platform: template
    name: "Call Elevator"
    on_press:
      - lambda: id(kocom).call_elevator();

binary_sensor:
  - platform: template
    name: "Elevator Called"
    lambda: return id(kocom).is_elevator_called();
